/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package toechart;

import java.awt.Color;

/**
 *
 * @author 0106267814
 */
public class DetailSummary extends javax.swing.JFrame {
    Login loginPage;
    /**
     * Creates new form DetailSummary
     */
    public DetailSummary() {
        initComponents();
        
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtEducationLevel = new javax.swing.JTextField();
        txtLandLine = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtAccountType = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Last Name* :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel7.setText("Phone Number :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 241, -1, 20));

        jLabel8.setText("Landline :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, -1, 30));

        jLabel5.setText("Address*:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 215, -1, 20));

        jLabel13.setText("Confirm Password* :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 20));

        jLabel6.setText("Level Of Education* :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 40));

        txtPhoneNumber.setBackground(java.awt.Color.gray);
        txtPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhoneNumber.setBorder(null);
        txtPhoneNumber.setOpaque(false);
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 240, 254, 20));

        jLabel4.setText("Date Of Birth* :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 163, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Summary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 33));

        txtAddress.setBackground(java.awt.Color.gray);
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.setBorder(null);
        txtAddress.setOpaque(false);
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 215, 254, 20));

        jLabel3.setText("First Name* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        txtFirstName.setBackground(java.awt.Color.gray);
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFirstName.setBorder(null);
        txtFirstName.setOpaque(false);
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 75, 254, 20));

        jLabel10.setText("Middle Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        txtEmail.setBackground(java.awt.Color.gray);
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 325, 254, 20));

        txtEducationLevel.setBackground(java.awt.Color.gray);
        txtEducationLevel.setForeground(new java.awt.Color(255, 255, 255));
        txtEducationLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEducationLevel.setBorder(null);
        txtEducationLevel.setOpaque(false);
        getContentPane().add(txtEducationLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 300, 254, 20));

        txtLandLine.setBackground(java.awt.Color.gray);
        txtLandLine.setForeground(new java.awt.Color(255, 255, 255));
        txtLandLine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLandLine.setBorder(null);
        txtLandLine.setOpaque(false);
        getContentPane().add(txtLandLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 270, 254, 20));

        txtLastName.setBackground(java.awt.Color.gray);
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLastName.setBorder(null);
        txtLastName.setOpaque(false);
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 104, 254, 20));

        txtMiddleName.setBackground(java.awt.Color.gray);
        txtMiddleName.setForeground(new java.awt.Color(255, 255, 255));
        txtMiddleName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMiddleName.setBorder(null);
        txtMiddleName.setOpaque(false);
        getContentPane().add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 133, 254, 20));

        txtGender.setBackground(java.awt.Color.gray);
        txtGender.setForeground(new java.awt.Color(255, 255, 255));
        txtGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGender.setBorder(null);
        txtGender.setOpaque(false);
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 190, 254, 20));

        jLabel11.setText("Email* :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 318, -1, 40));

        jLabel12.setText("Password* : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setForeground(new java.awt.Color(0, 0, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jLabel14.setText("Choose Account Type * :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 37, 160, 40));

        txtAccountType.setEditable(false);
        txtAccountType.setBackground(java.awt.Color.gray);
        txtAccountType.setForeground(new java.awt.Color(255, 255, 255));
        txtAccountType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountType.setBorder(null);
        txtAccountType.setOpaque(false);
        getContentPane().add(txtAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 46, 254, 20));

        jLabel16.setText("Gender* : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, -1, -1));

        txtDateOfBirth.setBackground(java.awt.Color.gray);
        txtDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        txtDateOfBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateOfBirth.setBorder(null);
        txtDateOfBirth.setOpaque(false);
        getContentPane().add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 162, 254, 20));

        txtPassword2.setBackground(java.awt.Color.gray);
        txtPassword2.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword2.setBorder(null);
        txtPassword2.setOpaque(false);
        getContentPane().add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 380, 260, 20));

        txtPassword1.setBackground(java.awt.Color.gray);
        txtPassword1.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword1.setBorder(null);
        txtPassword1.setOpaque(false);
        getContentPane().add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 350, 260, 20));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        DbConnect DB = new DbConnect();
        
        DB.insertToDatabase(txtFirstName.getText(), txtLastName.getText(), txtMiddleName.getText(), txtDateOfBirth.getText(), txtGender.getText(),  txtAddress.getText(), txtPhoneNumber.getText(), txtLandLine.getText(), txtEducationLevel.getText(), txtEmail.getText(), txtPassword1.getText(), txtAccountType.getText());
        if (loginPage == null) 
        {
            loginPage = new Login();
        }
        dispose();
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Registeration registrationForm = new Registeration();
        Registeration.cbxAccountType.setSelectedItem(this.txtAccountType.getText());
        Registeration.txtFirstName.setText(this.txtFirstName.getText());
        Registeration.txtLastName.setText(this.txtLastName.getText());
        Registeration.txtMiddleName.setText(this.txtMiddleName.getText());
        Registeration.cbxGender.setSelectedItem(this.txtGender.getText());
        Registeration.txtAddress.setText(this.txtAddress.getText());
        Registeration.txtDateOfBirth.setText(this.txtDateOfBirth.getText());
        Registeration.txtPhoneNumber.setText(this.txtPhoneNumber.getText());
        Registeration.txtLandLine.setText(this.txtLandLine.getText());
        Registeration.txtEducationLevel.setText(this.txtEducationLevel.getText());
        Registeration.txtPassword1.setText(this.txtPassword1.getText());
        Registeration.txtPassword2.setText(this.txtPassword2.getText());
        dispose();
        registrationForm.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtAccountType;
    public static javax.swing.JTextField txtAddress;
    public static javax.swing.JTextField txtDateOfBirth;
    public static javax.swing.JTextField txtEducationLevel;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtFirstName;
    public static javax.swing.JTextField txtGender;
    public static javax.swing.JTextField txtLandLine;
    public static javax.swing.JTextField txtLastName;
    public static javax.swing.JTextField txtMiddleName;
    public static javax.swing.JPasswordField txtPassword1;
    public static javax.swing.JPasswordField txtPassword2;
    public static javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
