/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package toechart;

import java.awt.Color;

/**
 *
 * @author 0106267814
 */
public class PathwayPage extends javax.swing.JFrame {
    Login loginPage;
    /**
     * Creates new form ad
     */
    public PathwayPage() {
        initComponents();
        cbxIndustries.removeAllItems();
        cbxCategories.removeAllItems();
        cbxPathway.removeAllItems();
        
        getContentPane().setBackground(Color.gray);
        
        DbConnect DB = new DbConnect();
        DB.industrySelect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxIndustries = new javax.swing.JComboBox();
        lblSignUp = new javax.swing.JLabel();
        cbxCategories = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxPathway = new javax.swing.JComboBox();
        btnEnter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("FINDMYCAREER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("___________________________________________________________________");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Industries :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cbxIndustries.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbxIndustries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select..." }));
        cbxIndustries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIndustriesActionPerformed(evt);
            }
        });
        getContentPane().add(cbxIndustries, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 84, 220, -1));

        lblSignUp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSignUp.setText("Sign Out.");
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 80, -1, -1));

        cbxCategories.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbxCategories.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select..." }));
        cbxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriesActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 220, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Categories :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Career Pathway :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, -1, -1));

        cbxPathway.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbxPathway.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select..." }));
        getContentPane().add(cbxPathway, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 220, -1));

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 70, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxIndustriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIndustriesActionPerformed
         //TODO add your handling code here:
        cbxCategories.removeAllItems();
        int id = cbxIndustries.getSelectedIndex();
        DbConnect DB = new DbConnect();
        DB.categorySelect(id);
    }//GEN-LAST:event_cbxIndustriesActionPerformed

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
        // TODO add your handling code here:
        if (loginPage == null)
        {
            loginPage = new Login();
        }
        dispose();
        loginPage.setVisible(true);
    }//GEN-LAST:event_lblSignUpMouseClicked

    private void cbxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriesActionPerformed
        // TODO add your handling code here:
        cbxPathway.removeAllItems();
        int indusID = cbxIndustries.getSelectedIndex();
        int catID = cbxCategories.getSelectedIndex();
        DbConnect DB = new DbConnect();
        DB.pathwaySelect(catID, indusID);
    }//GEN-LAST:event_cbxCategoriesActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        int pathID = cbxPathway.getSelectedIndex();
        int catID = cbxCategories.getSelectedIndex();
        DbConnect DB = new DbConnect();
        //DB.jobTable(catID, pathID);    
        
        SubPathwayPage jobPage = new SubPathwayPage();       
        jobPage.setVisible(true);
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PathwayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PathwayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PathwayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PathwayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PathwayPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    public static javax.swing.JComboBox cbxCategories;
    public static javax.swing.JComboBox cbxIndustries;
    public static javax.swing.JComboBox cbxPathway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblSignUp;
    // End of variables declaration//GEN-END:variables
}
